INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (1, 'Boiled Rice 1 KG pack', 50.00, 94);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (2, 'Boiled Rice 2 KG pack', 98.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (3, 'Boiled Rice 5 KG pack', 235.00, 80);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (4, 'Basmati Rice 1 KG pack', 55.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (5, 'Basmati Rice 2 KG pack', 104.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (6, 'Basmati Rice 5 KG pack', 255.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (7, 'Sona Masoori Rice 1 KG pack', 50.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (8, 'Sona Masoori Rice 2 KG pack', 100.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (9, 'Sona Masoori Rice 5 KG pack', 245.00, 58);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (10, 'Puffed Rice (200g)', 30.00, 54);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (11, 'Broom (Regular)', 30.00, 54);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (12, 'Kellogs Chocos (250g)', 137.00, 30);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (13, 'Apple', 80.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (14, 'Pineapple', 80.00, 30);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (15, 'Bananas', 40.00, 1200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (16, 'Orange', 80.00, 800);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (17, 'Mango', 35.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (18, 'Coconut', 50.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (19, 'Papaya', 55.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (20, 'Guava', 90.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (21, 'Watermelon', 100.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (22, 'Pomegranate', 180.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (23, 'Grapes', 90.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (24, 'Lemon', 10.00, 1300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (25, 'Spinach', 20.00, 700);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (26, 'Coriander', 10.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (27, 'Mint Leaves', 15.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (28, 'Okra (Bhindi)', 60.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (29, 'Bottle Gourd (Lauki)', 40.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (30, 'Bitter Gourd (Karela)', 50.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (31, 'Brinjal (Eggplant)', 60.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (32, 'Cauliflower', 70.00, 450);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (33, 'Cabbage', 30.00, 350);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (34, 'Green Beans', 60.00, 450);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (35, 'Potatoes', 20.00, 1500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (36, 'Tomatoes', 30.00, 1300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (37, 'Onions', 25.00, 1200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (38, 'Garlic', 100.00, 900);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (39, 'Ginger', 60.00, 800);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (40, 'Peas', 60.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (41, 'Green Chillies', 40.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (42, 'Carrots', 50.00, 700);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (43, 'Drumsticks (Moringa)', 120.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (44, 'Raw Mango', 80.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (45, 'Turmeric Root', 150.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (46, 'Atta (Wheat Flour)', 60.00, 800);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (47, 'Besan (Chickpea Flour)', 60.00, 700);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (48, 'Ragi Flour (Finger Millet)', 80.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (49, 'Poha (Flattened Rice)', 40.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (50, 'Suji (Semolina)', 40.00, 800);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (51, 'Urad Dal (Black Lentils)', 120.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (52, 'Toor Dal (Pigeon Pea)', 100.00, 350);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (53, 'Moong Dal (Yellow Lentils)', 110.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (54, 'Chana Dal (Bengal Gram)', 90.00, 750);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (55, 'Rajma (Kidney Beans)', 130.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (56, 'Chickpea (Kabuli Chana)', 90.00, 900);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (57, 'Sambar Powder', 40.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (58, 'Garam Masala', 80.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (59, 'Turmeric Powder', 40.00, 700);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (60, 'Coriander Powder', 50.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (61, 'Cumin Seeds', 50.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (62, 'Mustard Seeds', 40.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (63, 'Curry Leaves', 15.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (64, 'Red Chilli Powder', 80.00, 350);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (65, 'Cinnamon Sticks', 150.00, 250);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (66, 'Cardamom', 400.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (67, 'Cloves', 300.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (68, 'Black Pepper Corns', 200.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (69, 'Fenugreek Seeds', 40.00, 450);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (70, 'Asafoetida (Hing)', 90.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (71, 'Achaar (Pickle)', 60.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (72, 'Jaggery', 40.00, 350);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (73, 'Ghee', 500.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (74, 'Coconut Oil', 300.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (75, 'Mustard Oil', 180.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (76, 'Paneer', 250.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (77, 'Apple Cider Vinegar', 400.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (78, 'Curd (Yogurt)', 50.00, 500);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (79, 'Red Label Tea (Chai)', 150.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (80, 'Filter Coffee', 300.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (81, 'Lassi', 40.00, 400);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (82, 'Fennel Seeds (Saunf)', 80.00, 350);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (83, 'Papad', 50.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (84, 'Kesar (Saffron)', 600.00, 50);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (85, 'Kurkure', 20.00, 600);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (86, 'Pickle(mango)500g', 100.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (87, 'Pickle(lemon)500g', 90.00, 160);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (88, 'Honey 500g', 200.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (89, 'Potato Chips', 50.00, 220);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (90, 'Potato chips(salted)200g', 50.00, 150);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (91, 'Potato chips(spicy)200g', 55.00, 130);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (92, 'Cheese puffs 150g', 60.00, 120);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (93, 'Nachos(cheese)200g', 70.00, 100);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (94, 'Nachos(spicy)200g', 75.00, 110);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (95, 'Popcorn(butter)100g', 40.00, 200);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (96, 'Popcorn(caramel)100g', 45.00, 180);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (97, 'Dairy milk silk 50g', 20.00, 300);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (98, 'Gummy Bears 100g', 35.00, 170);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (99, 'Oreo Cookies 150g', 80.00, 140);
INSERT INTO products (product_id, product_name, price, stock_quantity) VALUES (100, 'Brownies 2pcs', 120.00, 80);
